server:
  port: 8080

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            Path=/user/**
        - id: CargoService
          uri: lb://CargoService
          predicates:
            Path=/cargo/**
      discovery:
        locator:
          enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true